### ISSUE TITLE
Mod Logo detection doesn't work properly

### ISSUE THREAD

**Issue by johfyakita** [Burgerballs/ModBootstrap#1]
Self Explanatory.

![image](https://github.com/Burgerballs/ModBootstrap/assets/85341402/c3cfe5cf-a262-45d6-af95-0e92cdda5242)

Modbind script for reference (if you don't believe me)

```
import funkin.modding.module.Module;
import funkin.modding.module.ModuleHandler;

class DokiModBind extends Module { // Replace the class name with a unique name of your choice
  public function new() {
      super("DokiModBind"); // Replace the string with a unique name of your choice
  }
  public function onCreate(event:ScriptEvent):Void {
    this.active = false;

    ModuleHandler.getModule("BootStrapBinds").scriptCall("bind", [{
        name: "Tomato Funkin'", // mod name
        description: "Boyfriend and Girlfriend are taking a stroll in an empty city when they saw a golden-haired lady singing in the middle of the road surrounded by round, horned, yellow birds acting as her audience. Boyfriend wants to sing (or rap) too, and what's better for him to scratch that itch is by challenging the lady to a rap battle.", // mod description
        target: "BaseTitleState", // target state
        bg: 'doki-bg', // if the bg is set to nothing, it will use the default bg
        icon: 'fnficon32', // path to icon (32x32)
        author: "Tomato Funkin' Devs", // name of the people who made the mod
        logo: 'dokifunk-logo', // big logo for the mod.
        color: 0xFFB00B69, // color for the selection tab thingies
        bg_group: (group) -> { // for dynamic bgs, to add stuff you must do "group.add(myVar)"
          return; // do nothing.
        },
        disclaimer: "Subscribe to Dokibird" // disclaimer, add anything you want here.
    }]);
  }
}
```

**Comment by Burgerballs** [comment]
> Self Explanatory.
> 
> ![image](https://private-user-images.githubusercontent.com/85341402/334334268-c3cfe5cf-a262-45d6-af95-0e92cdda5242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTMxNzksIm5iZiI6MTcxNjg5Mjg3OSwicGF0aCI6Ii84NTM0MTQwMi8zMzQzMzQyNjgtYzNjZmU1Y2YtYTI2Mi00NWQ2LWFmOTUtMGU5MmNkZGE1MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NGYwNzE5ZWY3NDEzNGE0MWJjZTNhMzI1NDBlYWUyMWU5MWEwNjg0NTM5OWJmZGQzNGUzZGI4YzQxNzM2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GkT4M346tOd9IiX41ed3kLPRMD2aiSzW1rzZAPecOVc)
> 
> Modbind script for reference (if you don't believe me)
> 
> ```
> import funkin.modding.module.Module;
> import funkin.modding.module.ModuleHandler;
> 
> class DokiModBind extends Module { // Replace the class name with a unique name of your choice
>   public function new() {
>       super("DokiModBind"); // Replace the string with a unique name of your choice
>   }
>   public function onCreate(event:ScriptEvent):Void {
>     this.active = false;
> 
>     ModuleHandler.getModule("BootStrapBinds").scriptCall("bind", [{
>         name: "Tomato Funkin'", // mod name
>         description: "Boyfriend and Girlfriend are taking a stroll in an empty city when they saw a golden-haired lady singing in the middle of the road surrounded by round, horned, yellow birds acting as her audience. Boyfriend wants to sing (or rap) too, and what's better for him to scratch that itch is by challenging the lady to a rap battle.", // mod description
>         target: "BaseTitleState", // target state
>         bg: 'doki-bg', // if the bg is set to nothing, it will use the default bg
>         icon: 'fnficon32', // path to icon (32x32)
>         author: "Tomato Funkin' Devs", // name of the people who made the mod
>         logo: 'dokifunk-logo', // big logo for the mod.
>         color: 0xFFB00B69, // color for the selection tab thingies
>         bg_group: (group) -> { // for dynamic bgs, to add stuff you must do "group.add(myVar)"
>           return; // do nothing.
>         },
>         disclaimer: "Subscribe to Dokibird" // disclaimer, add anything you want here.
>     }]);
>   }
> }
> ```

I will fix this bug later today, thanks for showing.

**Comment by Burgerballs** [comment]
Fixed, releasing on gamebanana
