### ISSUE TITLE
Disabling Mods Doesnt "Disable Them"

### ISSUE THREAD

**Issue by MemTheBun** [Burgerballs/ModBootstrap#6]
Like The Title Says

**Comment by Burgerballs** [comment]
Can you show anything, like at all?

**Comment by B3eper132** [comment]
Do they mean something like this?
It started happening to me when 4.0 dropped

https://github.com/Burgerballs/ModBootstrap/assets/145614528/1561be8c-923b-4b93-8261-bc29827cd184

**Comment by B3eper132** [comment]
Sorry if the video is weird, this was my first time recording using OBS.
